version: '3.8'

services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./packages/api:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/eudi_connect
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - DEBUG=1
      - SECRET_KEY=development_secret_key
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis
      - jaeger

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eudi_connect
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  redis_data:
