name: EUDI-Connect API Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/api/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: eudi_connect_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd packages/api
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-randomly python-dotenv
          
      - name: Create test key file
        run: |
          mkdir -p packages/api/tests/data
          echo '{"kty":"OKP","crv":"Ed25519","x":"11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo","d":"nWGxne_9WmC6hEr0kuwsxERJxWl7MmkZcDusAxyuf2A"}' > packages/api/tests/data/didkit_test_key.json
          
      - name: Set up .env.test
        run: |
          cat > packages/api/.env.test << EOL
          PROJECT_NAME=EUDI-Connect-Test
          VERSION=0.1.0
          API_V1_STR=/api/v1
          SECRET_KEY=test-ci-key-123
          ACCESS_TOKEN_EXPIRE_MINUTES=30
          REFRESH_TOKEN_EXPIRE_DAYS=7
          
          # Database settings
          POSTGRES_HOST=localhost
          POSTGRES_PORT=5432
          POSTGRES_USER=test
          POSTGRES_PASSWORD=test
          POSTGRES_DB=eudi_connect_test
          
          # DIDKit settings
          DIDKIT_KEY_PATH=tests/data/didkit_test_key.json
          
          # SQLAlchemy async URI for tests
          DATABASE_URI=postgresql+asyncpg://test:test@localhost:5432/eudi_connect_test
          EOL
          
      - name: Run tests with coverage
        run: |
          cd packages/api
          PYTHONPATH=. pytest tests/api/v1 --cov=eudi_connect --cov-report=xml --cov-report=term -v
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./packages/api/coverage.xml
          fail_ci_if_error: false
          flags: unittests
          name: eudi-connect-codecov
